export const CATEGORIES = ["Tất cả", "EdTech", "AI & ML", "SaaS", "FinTech", "Gọi vốn Seed", "Founder Tips", "Mentor Advice"];

export const DISCOVER_FEED = [
    {
        id: 1,
        author: { name: "Alex Hormozi", handle: "@ahormozi", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=64&q=80" },
        time: "1h",
        content: "Just migrated our entire backend architecture to SpacetimeDB. The real-time data sync is unbelievably smooth compared to our old custom infrastructure. If you're building multiplayer tools or apps that need zero-latency sync, check it out. 🔥",
        image: null,
        metrics: { views: "45K", likes: "2.1K", comments: "182" },
        tag: "TECH UPDATE",
        highlight: "Realtime"
    },
    {
        id: 2,
        author: { name: "Jessica Livingston", handle: "@jessy_yc", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=64&q=80" },
        time: "3h",
        content: "The EdTech market in 2026 has no room for platforms just selling video courses. AI-Tutoring and Real-time Mentorship are the real game changers.\n\nLooking to fund 2 AI Edtech teams for our upcoming Pre-Seed batch ($50k - $100k).",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "65K", likes: "3.2K", comments: "428" },
        tag: "CALL FOR PITCH",
        highlight: "$100K"
    },
    {
        id: 3,
        author: { name: "Sam Altman", handle: "@sama", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=64&q=80" },
        time: "4h",
        content: "The new agentic frameworks we're seeing on Kizuna Hub are incredibly promising. Splitting complex tasks among specialized micro-agents is far more efficient than relying on one massive LLM. The latency reduction is significant.",
        image: null,
        metrics: { views: "112K", likes: "8.4K", comments: "912" },
        tag: "AI RESEARCH",
        highlight: "Hot 🔥"
    },
    {
        id: 4,
        author: { name: "Helena Turpin", handle: "@helenat_fin", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=64&q=80" },
        time: "7h",
        content: "We just launched the 'Zero-Click Traction' feature! It automatically syncs your Stripe MRR and GA4 data directly to your investor dashboard. Absolute transparency for your seed rounds.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "18K", likes: "890", comments: "56" },
        tag: "PLATFORM",
        highlight: "New"
    },
    {
        id: 5,
        author: { name: "Paul Graham", handle: "@paulg", avatar: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?auto=format&fit=crop&w=64&q=80" },
        time: "9h",
        content: "The biggest mistake student founders make: Focusing too much on writing code and completely forgetting to validate the idea.\n\nIf you can't sell your vision with a simple Google Form, coding a shiny app is useless. Do things that don't scale first.",
        image: null,
        metrics: { views: "82K", likes: "5.5K", comments: "312" },
        tag: "FOUNDER TIPS",
    },
    {
        id: 6,
        author: { name: "Diana Kew", handle: "@dkew_growth", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=64&q=80" },
        time: "12h",
        content: "Month 2 of our Open Beta: We just crossed 10,000 MAU! Our Week-1 Retention Rate stabilized at 48%. The AI Shadowing feature for pronunciation grading is hitting 94% accuracy. Massive thanks to the Kizuna mentors for the brutal UI/UX feedback!",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "25K", likes: "1.4K", comments: "89" },
        tag: "MILESTONE",
        highlight: "10k MAU"
    },
    {
        id: 7,
        author: { name: "Logan Paul", handle: "@loganp", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=64&q=80" },
        time: "18h",
        content: "Just finalized the brackets for the IT League 2026 platform. The AI is now automatically allocating referee budgets and generating player stats post-match. We are looking for one solid Data Analyst to join the founding team.",
        image: null,
        metrics: { views: "34K", likes: "1.1K", comments: "102" },
        tag: "HIRING",
    },
    {
        id: 8,
        author: { name: "Sachin Chhabra", handle: "@sachin_med", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=64&q=80" },
        time: "1d",
        content: "Case Study: How we scaled to our first $5,000 MRR with just 2 devs and $0 in marketing spend. The secret was leveraging the B2B network on Kizuna Hub and offering a lifetime deal to our first 50 enterprise users.",
        image: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "41K", likes: "2.8K", comments: "215" },
        tag: "CASE STUDY",
        highlight: "$5K MRR"
    },
    {
        id: 9,
        author: { name: "Kain Seo", handle: "@kainseo", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=64&q=80" },
        time: "1d",
        content: "Stop building monolithic applications for SaaS MVPs. Micro-frontends paired with a modular monolith backend is the sweet spot for startups moving fast while preparing for scale.",
        image: null,
        metrics: { views: "19K", likes: "840", comments: "95" },
        tag: "ENGINEERING",
    },
    {
        id: 10,
        author: { name: "Anurag Singh", handle: "@anurag_vc", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=64&q=80" },
        time: "2d",
        content: "Reviewed over 40 pitch decks this week on the hub. The ones that stand out immediately are those with clear Go-To-Market (GTM) strategies. Stop talking about your code for 15 slides. Tell me how you acquire users.",
        image: null,
        metrics: { views: "28K", likes: "1.7K", comments: "134" },
        tag: "MENTOR ADVICE",
    },
    {
        id: 11,
        author: { name: "Shobini Appanderanda", handle: "@shobini", avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=64&q=80" },
        time: "2d",
        content: "Our cybersecurity dashboard just got a massive UI overhaul. Transitioned completely to a white bento grid layout. The cognitive load on our users dropped by 60% according to our latest UX testing metrics.",
        image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "14K", likes: "620", comments: "41" },
        tag: "DESIGN",
        highlight: "UX Update"
    },
    {
        id: 12,
        author: { name: "Farhan Kalim", handle: "@fkalim", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=64&q=80" },
        time: "3d",
        content: "If your AI wrapper doesn't have a proprietary data moat, you don't have a startup. You have a temporary feature that OpenAI will wipe out in their next update. Build workflow integrations, not just chat UI.",
        image: null,
        metrics: { views: "56K", likes: "4.9K", comments: "389" },
        tag: "AI STRATEGY",
    },
    {
        id: 13,
        author: { name: "Bradley Ochilien", handle: "@bradoch", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=64&q=80" },
        time: "3d",
        content: "E-commerce infrastructure is shifting heavily towards headless architectures. We just helped a Shopify Plus brand cut their load times by 70% using Next.js and Vercel. Performance is revenue.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "22K", likes: "1.1K", comments: "88" },
        tag: "E-COMMERCE",
    },
    {
        id: 14,
        author: { name: "Rohan Chandhok", handle: "@rohan_sec", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=64&q=80" },
        time: "4d",
        content: "Seed valuations are correcting. We're seeing realistic $4M-$6M caps instead of the insane $15M+ we saw last year. It's a healthy reset for the ecosystem. Good founders will still get funded.",
        image: null,
        metrics: { views: "31K", likes: "2.3K", comments: "210" },
        tag: "VENTURE CAPITAL",
        highlight: "Insight"
    },
    {
        id: 15,
        author: { name: "Allan Khazak", handle: "@allank", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=64&q=80" },
        time: "5d",
        content: "Finished integrating the new modular monolith agent toolkit. Being able to automate repetitive workflow tasks across 5 different platforms without writing glue code is a superpower.",
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=600&q=80",
        metrics: { views: "16K", likes: "750", comments: "62" },
        tag: "AUTOMATION",
    },
    {
        id: 16,
        author: { name: "Vijay Ramachandran", handle: "@vijay_data", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=64&q=80" },
        time: "5d",
        content: "Data pipelines shouldn't be brittle. If your ETL breaks every time a schema changes, you need to look into data contracts. It completely saved our engineering team from late-night debugging sessions.",
        image: null,
        metrics: { views: "12K", likes: "480", comments: "39" },
        tag: "DATA ENG",
    }
];