export const myProductsData = [
  {
    id: "p1",
    name: "Kizuna Hub",
    tagline: "Mentor-readiness workspace for student founders",
    logo: "https://images.unsplash.com/photo-1556761175-5973dc0f32b7?q=80&w=300",
    color: "bg-[#081810]",
    categories: ["B2B SaaS", "Founder tooling"],
    stage: "Pilot / Early users",
    mentor: "Dr. Alex Chen",
    approvalStatus: "Published",
    traction: {
      status: "Funded",
      amount: "$50K",
      round: "Pre-Seed",
    },
    stats: {
      views: 1240,
      upvotes: 342,
    },
    updatedAt: "AI readiness review updated 2 hours ago",
  },
  {
    id: "p2",
    name: "SnapMoney",
    tagline: "AI-assisted personal spending coach from receipt photos",
    logo: "https://images.unsplash.com/photo-1542382257-80dedb725088?q=80&w=300",
    color: "bg-amber-400",
    categories: ["FinTech", "Consumer"],
    stage: "Prototype / MVP",
    mentor: "Tran Minh",
    approvalStatus: "Pending",
    traction: {
      status: "Seeking",
      amount: "$100K",
      round: "Seed",
    },
    stats: {
      views: 890,
      upvotes: 156,
    },
    updatedAt: "Startup profile needs customer evidence",
  },
  {
    id: "p3",
    name: "Dietfit AI",
    tagline: "Personalized nutrition assistant powered by computer vision",
    logo: "https://images.unsplash.com/photo-1512314889357-e157c22f938d?q=80&w=300",
    color: "bg-orange-500",
    categories: ["HealthTech", "AI"],
    stage: "Idea",
    mentor: "No mentor yet",
    approvalStatus: "Rejected",
    traction: {
      status: "Bootstrapped",
      amount: "$0",
      round: "N/A",
    },
    stats: {
      views: 430,
      upvotes: 89,
    },
    updatedAt: "Data Room checklist has missing documents",
  },
];
