import type {
  AccentAppearanceTokens,
  AccentThemeDefinition,
  AccentThemeId,
  ResolvedAppearance,
} from "../types/theme.types";

export const ACCENT_BASE_COLORS = {
  kizuna: "#CC785C",
  ocean: "#4F8FB8",
  violet: "#8B78C6",
  amber: "#C58A3B",
  rose: "#B96779",
  graphite: "#7C858C",
  monochrome: "#30302E",
} as const satisfies Record<AccentThemeId, string>;

export const ACCENT_THEMES: AccentThemeDefinition[] = [
  {
    id: "kizuna",
    label: "Kizuna",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.kizuna,
    light: {
      primary: "#CC785C",
      primaryHover: "#B9674F",
      primaryActive: "#A55641",
      primaryForeground: "#FFFFFF",
      primaryAction: "#A9533D",
      primaryActionHover: "#974833",
      primaryActionActive: "#823C2A",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#713625",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#93442F",
      ring: "#B95E45",
      selection: "rgba(204, 120, 92, 0.28)",
    },
    dark: {
      primary: "#D98A70",
      primaryHover: "#E49A83",
      primaryActive: "#C97860",
      primaryForeground: "#FFFFFF",
      primaryAction: "#D98A70",
      primaryActionHover: "#E49A83",
      primaryActionActive: "#C97860",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "#2A1A15",
      primaryMutedHover: "#36221B",
      primaryMutedForeground: "#F0B39E",
      primaryBorder: "#704233",
      primaryText: "#E8A18A",
      ring: "#DD9077",
      selection: "rgba(217, 138, 112, 0.3)",
    },
  },
  {
    id: "ocean",
    label: "Ocean",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.ocean,
    light: {
      primary: "#4F8FB8",
      primaryHover: "#3E7EA7",
      primaryActive: "#326B90",
      primaryForeground: "#FFFFFF",
      primaryAction: "#326786",
      primaryActionHover: "#285873",
      primaryActionActive: "#21495F",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#244F68",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#27607F",
      ring: "#39799F",
      selection: "rgba(79, 143, 184, 0.26)",
    },
    dark: {
      primary: "#72ADD0",
      primaryHover: "#85BBDD",
      primaryActive: "#6099BC",
      primaryForeground: "#FFFFFF",
      primaryAction: "#72ADD0",
      primaryActionHover: "#85BBDD",
      primaryActionActive: "#6099BC",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "#14232C",
      primaryMutedHover: "#1B303C",
      primaryMutedForeground: "#A9D1E8",
      primaryBorder: "#355D73",
      primaryText: "#8DC3E0",
      ring: "#78B4D7",
      selection: "rgba(114, 173, 208, 0.28)",
    },
  },
  {
    id: "violet",
    label: "Violet",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.violet,
    light: {
      primary: "#8B78C6",
      primaryHover: "#7965B5",
      primaryActive: "#6855A2",
      primaryForeground: "#FFFFFF",
      primaryAction: "#6551A2",
      primaryActionHover: "#56448F",
      primaryActionActive: "#493A79",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#514180",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#5C4895",
      ring: "#725EAE",
      selection: "rgba(139, 120, 198, 0.26)",
    },
    dark: {
      primary: "#AC9ADE",
      primaryHover: "#BAAAE7",
      primaryActive: "#9986CF",
      primaryForeground: "#FFFFFF",
      primaryAction: "#AC9ADE",
      primaryActionHover: "#BAAAE7",
      primaryActionActive: "#9986CF",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "#211C31",
      primaryMutedHover: "#2C2640",
      primaryMutedForeground: "#D2C7EF",
      primaryBorder: "#534575",
      primaryText: "#BDAEE8",
      ring: "#B2A1E4",
      selection: "rgba(172, 154, 222, 0.28)",
    },
  },
  {
    id: "amber",
    label: "Amber",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.amber,
    light: {
      primary: "#C58A3B",
      primaryHover: "#AE762E",
      primaryActive: "#966323",
      primaryForeground: "#FFFFFF",
      primaryAction: "#87570F",
      primaryActionHover: "#744A0C",
      primaryActionActive: "#633E09",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#67420E",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#80510E",
      ring: "#A46E24",
      selection: "rgba(197, 138, 59, 0.27)",
    },
    dark: {
      primary: "#D9A24F",
      primaryHover: "#E4B263",
      primaryActive: "#C28D3E",
      primaryForeground: "#FFFFFF",
      primaryAction: "#D9A24F",
      primaryActionHover: "#E4B263",
      primaryActionActive: "#C28D3E",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "#2B2112",
      primaryMutedHover: "#392B17",
      primaryMutedForeground: "#F0C886",
      primaryBorder: "#6B5126",
      primaryText: "#E7B967",
      ring: "#DEA958",
      selection: "rgba(217, 162, 79, 0.28)",
    },
  },
  {
    id: "rose",
    label: "Rose",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.rose,
    light: {
      primary: "#B96779",
      primaryHover: "#A65567",
      primaryActive: "#914657",
      primaryForeground: "#FFFFFF",
      primaryAction: "#8C4455",
      primaryActionHover: "#793848",
      primaryActionActive: "#672E3C",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#713846",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#873F50",
      ring: "#A75265",
      selection: "rgba(185, 103, 121, 0.26)",
    },
    dark: {
      primary: "#D18394",
      primaryHover: "#DC94A4",
      primaryActive: "#BE7081",
      primaryForeground: "#FFFFFF",
      primaryAction: "#D18394",
      primaryActionHover: "#DC94A4",
      primaryActionActive: "#BE7081",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "#2B1A1E",
      primaryMutedHover: "#392228",
      primaryMutedForeground: "#EAB4C0",
      primaryBorder: "#6B3D48",
      primaryText: "#DD9EAC",
      ring: "#D7899A",
      selection: "rgba(209, 131, 148, 0.28)",
    },
  },
  {
    id: "graphite",
    label: "Graphite",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.graphite,
    light: {
      primary: "#7C858C",
      primaryHover: "#687279",
      primaryActive: "#596269",
      primaryForeground: "#FFFFFF",
      primaryAction: "#555F66",
      primaryActionHover: "#475158",
      primaryActionActive: "#3A4349",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#434B50",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#4F5960",
      ring: "#68747B",
      selection: "rgba(124, 133, 140, 0.25)",
    },
    dark: {
      primary: "#A7B0B5",
      primaryHover: "#B7BFC4",
      primaryActive: "#949EA4",
      primaryForeground: "#151719",
      primaryAction: "#A7B0B5",
      primaryActionHover: "#B7BFC4",
      primaryActionActive: "#949EA4",
      primaryActionForeground: "#151719",
      primaryMuted: "#202426",
      primaryMutedHover: "#2A3033",
      primaryMutedForeground: "#D0D5D8",
      primaryBorder: "#515A5F",
      primaryText: "#BBC3C7",
      ring: "#ADB6BB",
      selection: "rgba(167, 176, 181, 0.27)",
    },
  },
  {
    id: "monochrome",
    label: "Monochrome",
    previewLabel: "Aa",
    baseColor: ACCENT_BASE_COLORS.monochrome,
    light: {
      primary: "#30302E",
      primaryHover: "#242422",
      primaryActive: "#181817",
      primaryForeground: "#FFFFFF",
      primaryAction: "#30302E",
      primaryActionHover: "#242422",
      primaryActionActive: "#181817",
      primaryActionForeground: "#FFFFFF",
      primaryMuted: "color-mix(in oklab, var(--color-primary) 8%, transparent)",
      primaryMutedHover: "color-mix(in oklab, var(--color-primary) 12%, transparent)",
      primaryMutedForeground: "#30302E",
      primaryBorder: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
      primaryText: "#30302E",
      ring: "#4A4946",
      selection: "rgba(48, 48, 46, 0.22)",
    },
    dark: {
      primary: "#D6D6D2",
      primaryHover: "#E3E3DF",
      primaryActive: "#C3C3BE",
      primaryForeground: "#151513",
      primaryAction: "#D6D6D2",
      primaryActionHover: "#E3E3DF",
      primaryActionActive: "#C3C3BE",
      primaryActionForeground: "#151513",
      primaryMuted: "#252522",
      primaryMutedHover: "#31312D",
      primaryMutedForeground: "#ECECE8",
      primaryBorder: "#62625C",
      primaryText: "#E0E0DC",
      ring: "#D6D6D2",
      selection: "rgba(214, 214, 210, 0.24)",
    },
  },
];

const themeById = new Map(
  ACCENT_THEMES.map((theme) => [theme.id, theme]),
);

export function getAccentThemeDefinition(id: AccentThemeId) {
  return themeById.get(id) ?? ACCENT_THEMES[0];
}

export function getAccentAppearanceTokens(
  id: AccentThemeId,
  appearance: ResolvedAppearance,
) {
  return getAccentThemeDefinition(id)[appearance];
}

export function accentTokensToCssVariables(
  tokens: AccentAppearanceTokens,
) {
  return {
    "--color-primary": tokens.primary,
    "--color-primary-hover": tokens.primaryHover,
    "--color-primary-active": tokens.primaryActive,
    "--color-primary-foreground": tokens.primaryForeground,
    "--color-primary-action": tokens.primaryAction,
    "--color-primary-action-hover": tokens.primaryActionHover,
    "--color-primary-action-active": tokens.primaryActionActive,
    "--color-on-primary": tokens.primaryActionForeground,
    "--color-primary-soft": tokens.primaryMuted,
    "--color-primary-muted": tokens.primaryMuted,
    "--color-primary-muted-hover": tokens.primaryMutedHover,
    "--color-primary-muted-foreground":
      tokens.primaryMutedForeground,
    "--color-primary-border": tokens.primaryBorder,
    "--color-primary-text": tokens.primaryText,
    "--color-ring": tokens.ring,
    "--color-accent": tokens.primary,
    "--color-accent-foreground": tokens.primaryForeground,
    "--workspace-selected": tokens.primaryMuted,
    "--workspace-focus-ring": tokens.ring,
    "--selection": tokens.selection,
  } as const;
}
