import type { AiWorkspaceCopy } from "./types";

export const aiWorkspaceVi: AiWorkspaceCopy = {
  workspace: {
    eyebrow: "Không gian làm việc cho Founder",
    title: "Trợ lý quyết định",
    description:
      "Đồng hành cùng bạn để làm rõ vấn đề và hành động đúng lúc.",
    demoLabel: "Bản demo cục bộ",
    scenarioLabel: "Kịch bản demo",
    reset: "Đặt lại bản demo",
    openPulse: "Mở Venture Pulse",
    backToConversation: "Quay lại hội thoại",
    loading: "Đang khôi phục bản demo…",
    noVentureTitle: "Hãy tạo dự án đầu tiên để bắt đầu hội thoại",
    createProject: "Tạo dự án",
  },
  scenarios: {
    "onboarding-case-study": "Onboarding activation · Hội thoại trước",
    bottleneck: "Tìm điểm nghẽn",
    materials: "Phân tích tài liệu",
    readiness: "Giải thích mức sẵn sàng",
    "decision-cycle": "Chu kỳ quyết định",
    mentor: "Cần góc nhìn chuyên gia",
    error: "Lỗi mô phỏng và thử lại",
    "long-running": "Venture dài hạn",
    "search-pricing": "Tìm quyết định pricing cũ",
    "context-conflict": "Mâu thuẫn khách hàng mục tiêu",
    "stale-traction": "Traction đã cũ",
    "readiness-decrease": "Readiness giảm",
    "safe-switch": "Đổi venture khi AI đang phản hồi",
    "search-ask": "Tìm kiếm và hỏi Kizuna",
    "session-summary": "Tóm tắt phiên làm việc",
    "failed-response": "Phản hồi AI thất bại",
  },
  chat: {
    regionLabel: "Hội thoại với trợ lý Kizuna",
    emptyTitle: "Bắt đầu từ điều đang khiến bạn phân vân",
    emptyDescription:
      "Kizuna sẽ làm rõ điểm nghẽn, nguồn dữ liệu và hành động nhỏ nhất tạo ra bằng chứng.",
    composerLabel: "Tin nhắn cho trợ lý Kizuna",
    composerPlaceholder: "Mô tả điều bạn đang cần làm rõ…",
    send: "Gửi",
    sending: "Đang phản hồi",
    voiceInput: "Nhập bằng giọng nói",
    voiceListening: "Đang nghe… Bắt đầu nói khi bạn sẵn sàng.",
    voiceUnsupported:
      "Trình duyệt này chưa hỗ trợ nhập bằng giọng nói.",
    voiceError:
      "Không thể truy cập microphone. Hãy kiểm tra quyền của trình duyệt.",
    voiceNoSpeech: "Chưa nhận được giọng nói. Hãy thử lại.",
    attach: "Đính kèm tài liệu",
    attachmentMenuLabel: "Chọn tài liệu để phân tích",
    sampleMaterials: "Tài liệu mẫu",
    selectedMaterials: "Tài liệu đã chọn",
    removeAttachment: "Bỏ tài liệu",
    attachmentLimit: "PDF, DOCX, PPTX · tối đa 3 tệp",
    typing: "Kizuna đang xem lại bối cảnh…",
    thinkingTitle: "Đang suy nghĩ",
    thoughtFor: "Đã suy nghĩ trong {seconds} giây",
    thinkingTasks: {
      understandRequest: "Làm rõ điều bạn đang cần",
      reviewContext: "Đối chiếu Venture Memory và bối cảnh hiện tại",
      reviewEvidence: "Kiểm tra bằng chứng liên quan",
      reviewMaterials: "Đọc tài liệu đã đính kèm",
      evaluateMentorNeed: "Đánh giá nhu cầu góc nhìn chuyên gia",
      planNextAction: "Xác định hành động hữu ích tiếp theo",
      composeResponse: "Soạn phản hồi",
    },
    retry: "Thử lại",
    messageSendFailed: "Tin nhắn chưa được gửi.",
    incompleteResponse:
      "Phản hồi chưa hoàn tất. Phần nội dung đã nhận được giữ nguyên.",
    errorFallback:
      "Phân tích mô phỏng chưa hoàn tất. Tin nhắn của bạn vẫn được giữ lại.",
    founderLabel: "Bạn",
    assistantLabel: "Kizuna",
    suggestedPromptsLabel: "Gợi ý câu hỏi",
    analyzeSelected: "Phân tích tài liệu đã chọn",
  },
  response: {
    insightDetected: "Điểm nghẽn được phát hiện",
    viewEvidence: "Xem bằng chứng",
    actionProposal: "Hành động đề xuất",
    editProposal: "Chỉnh đề xuất",
    cycleCreated: "Đã tạo chu kỳ quyết định",
    currentStep: "Bước hiện tại",
    artifactCompleted: "Đã hoàn tất",
    openAnalysis: "Mở bản phân tích",
    superseded: "Kết luận này đã được thay thế bởi một phân tích mới hơn.",
    dismissed: "Đề xuất này đã được bỏ qua.",
    sourceSummary: (total, verified) =>
      `Dựa trên ${total} nguồn · ${verified} nguồn đã xác minh`,
    mentorBooked: (name) =>
      `Đã đặt lịch trao đổi với ${name}`,
    ownMentorPreparation:
      "Đã mở phần chuẩn bị với cố vấn hiện tại",
    currentFocus: "Trọng tâm hiện tại",
    bottleneck: "Điểm nghẽn",
    whyItMatters: "Vì sao điều này quan trọng",
    nextAction: "Hành động tiếp theo",
    sources: "Nguồn và mức độ tin cậy",
    openCycle: "Mở chu kỳ quyết định",
    explainConclusion: "Giải thích kết luận",
    viewSources: "Xem nguồn",
    materialAnalysis: "Phân tích tài liệu",
    confirmInterpretation: "Xác nhận cách AI hiểu",
    challengeInterpretation: "Phản biện kết luận",
    createCycle: "Tạo chu kỳ quyết định",
    readiness: "Mức độ sẵn sàng",
    currentScore: "Điểm hiện tại",
    cycleChange: "Thay đổi trong chu kỳ",
    pointsFromEvidence: "điểm từ bằng chứng mới",
    breakdown: "Chi tiết theo thành phần",
    supportedBy: "Được hỗ trợ bởi",
    missingEvidence: "Bằng chứng còn thiếu",
    unlockAction: "Hành động mở khóa bước tiếp theo",
    evidenceReview: "Review bằng chứng",
    mentorRecommendation: "Nên có góc nhìn từ chuyên gia",
    whyHumanNow: "Vì sao cần con người lúc này",
    whyThisMentor: "Vì sao cố vấn này phù hợp",
    expectedOutcome: "Kết quả kỳ vọng",
    viewFit: "Xem mức độ phù hợp",
    defer: "Để sau",
    noMentorNeeded: "Chưa cần cố vấn ở thời điểm này",
    mentorDeferred: "Đã để đề xuất cố vấn lại sau",
    interpretationConfirmed: "Cách hiểu này đã được founder xác nhận",
    interpretationDisputed: "Phản biện của founder đã được ghi nhận",
  },
  pulse: {
    title: "Venture Pulse",
    readiness: "Mức độ sẵn sàng",
    explain: "Xem giải thích",
    currentFocus: "Trọng tâm hiện tại",
    evidenceHealth: "Tình trạng bằng chứng",
    humanInput: "Góc nhìn chuyên gia",
    noMentor:
      "AI vẫn có thể giúp bạn thu hẹp vấn đề trước khi cần thêm góc nhìn bên ngoài.",
    cycleProgress: "Tiến độ chu kỳ",
    focusUnknown: "Chưa xác định",
    noActiveCycle: "Chưa có chu kỳ quyết định đang chạy",
    activeCycle: "Chu kỳ đang chạy",
    cycleStep: "Bước",
    action: "Hành động",
  },
  mentor: {
    panelTitle: "Cố vấn phù hợp với quyết định này",
    backToPulse: "Quay lại Venture Pulse",
    recommendationStatus: "Đề xuất theo blocker hiện tại",
    savedStatus: "Đã lưu để xem lại",
    bookedStatus: "Đã đặt lịch",
    externalStatus: "Đang chuẩn bị với cố vấn của bạn",
    staleStatus: "Đề xuất cần được phân tích lại",
    matchRationale: "Vì sao phù hợp",
    whyNow: "Vì sao cần lúc này",
    expectedOutcomes: "Kết quả kỳ vọng",
    preparation: "Chuẩn bị trước phiên",
    availability: "Lịch phù hợp",
    decisionScope: "Phạm vi quyết định",
    bookSession: "Đặt lịch trao đổi",
    saveForLater: "Lưu lại",
    savedForLater: "Đã lưu",
    notSuitable: "Không phù hợp",
    useOwnMentor: "Tôi đã có cố vấn",
    continueWithAi: "Tiếp tục với AI",
    compareAlternatives: "So sánh 2 lựa chọn khác",
    alternativeStrength: "Điểm mạnh",
    alternativeTradeOff: "Trade-off",
    sessionPreparation: "Chuẩn bị phiên cố vấn",
    preparationProgress: "mục đã hoàn tất",
    bookingConfirmed:
      "Phiên demo đã được ghi nhận. Hoàn thiện brief trước khi trao đổi.",
    bookingTime: "Thời gian",
    sessionGoal: "Mục tiêu",
    openSessionBrief: "Mở brief phiên",
    externalPreparation:
      "Kizuna sẽ giúp chuẩn bị context, câu hỏi và bằng chứng cho cố vấn hiện tại của bạn.",
    refreshRecommendation: "Phân tích lại cố vấn phù hợp",
    staleExplanation:
      "Blocker hoặc chu kỳ quyết định đã thay đổi kể từ khi đề xuất này được tạo.",
    dismissReasons: {
      not_now: "Không cần lúc này",
      not_fit: "Không phù hợp chuyên môn",
      already_supported: "Tôi đã có người hỗ trợ",
      try_first: "Muốn tự thử trước",
    },
  },
  cycle: {
    eyebrow: "Chu kỳ quyết định",
    title: "Biến một giả định thành bằng chứng có thể review",
    description:
      "Mỗi lần chỉ mở một bước. Các bước hoàn tất được giữ lại dưới dạng tóm tắt.",
    steps: {
      understand: {
        label: "Hiểu vấn đề",
        description: "Làm rõ điểm nghẽn và điều đang được giả định.",
      },
      decide: {
        label: "Chọn quyết định",
        description: "Chốt một quyết định có thể kiểm chứng.",
      },
      act: {
        label: "Hành động",
        description: "Thực hiện thử nghiệm nhỏ nhất tạo ra tín hiệu.",
      },
      evidence: {
        label: "Thu thập bằng chứng",
        description: "Gắn dữ liệu thực tế với tiêu chí thành công.",
      },
      review: {
        label: "Review và học hỏi",
        description: "Đọc kết quả, cập nhật readiness và chọn bước tiếp.",
      },
    },
    goal: "Mục tiêu",
    chosenAction: "Hành động đã chọn",
    expectedOutcome: "Kết quả kỳ vọng",
    primaryMetric: "Chỉ số chính",
    checklist: "Checklist thực thi",
    evidence: "Bằng chứng",
    continue: "Tiếp tục bước kế",
    submitEvidence: "Nộp bằng chứng mẫu",
    evidenceSubmitted: "Bằng chứng đã được ghi nhận",
    requestReview: "Yêu cầu AI review",
    reviewComplete: "Review đã hoàn tất",
    reviewing: "Kizuna đang review bằng chứng…",
    completeChecklistHint:
      "Hoàn tất các việc trong checklist trước khi chuyển sang thu thập bằng chứng.",
    evidenceHint:
      "Dùng bộ bằng chứng mẫu để mô phỏng một vòng review hoàn chỉnh.",
    completed: "Đã hoàn tất",
    current: "Đang thực hiện",
    locked: "Chưa mở",
  },
  statuses: {
    verified: "Đã xác minh",
    inferred: "AI suy luận",
    assumed: "Giả định",
    missing: "Còn thiếu",
    disputed: "Đang tranh luận",
    outdated: "Đã cũ",
    waiting: "Đang chờ",
  },
  prompts: {
    explainBottleneck:
      "Vì sao đây là điểm nghẽn quan trọng nhất?",
    challengeInterpretation:
      "Tôi muốn phản biện cách AI hiểu startup",
    explainReadiness: "Vì sao mức độ sẵn sàng đang thấp?",
    recommendMentor: "Đề xuất cố vấn phù hợp",
  },
  longRun: {
    common: {
      close: "Đóng",
      cancel: "Hủy",
      save: "Lưu",
      edit: "Chỉnh sửa",
      delete: "Xóa",
      retry: "Thử lại",
      openSource: "Mở nguồn",
      viewContext: "Xem trong ngữ cảnh",
      askKizuna: "Hỏi Kizuna",
      pin: "Ghim",
      unpin: "Bỏ ghim",
      more: "Thêm tùy chọn",
    },
    sidebar: {
      backToProjects: "Quay lại Projects",
      newConversation: "Cuộc trò chuyện mới",
      searchVenture: "Tìm kiếm trong venture",
      today: "Hôm nay",
      recent: "7 ngày qua",
      older: "Trước đó",
      decisionCycles: "Chu kỳ quyết định",
      pinned: "Đã ghim",
      materials: "Tài liệu",
      network: "Mạng lưới",
      conversationOptions: "Tùy chọn cuộc trò chuyện",
      rename: "Đổi tên",
      deleteConversation: "Xóa đoạn chat",
      archive: "Lưu trữ",
      noConversations: "Chưa có cuộc trò chuyện",
      expand: "Mở rộng thanh bên",
      collapse: "Thu gọn thanh bên",
    },
    conversation: {
      scope: "Phạm vi hội thoại",
      search: "Tìm trong cuộc trò chuyện",
      summarize: "Tóm tắt phiên làm việc",
      memory: "Bộ nhớ venture",
      timeline: "Dòng thời gian quyết định",
      noMatches: "Không tìm thấy kết quả trong phiên này",
      resultCount: (current, total) => `${current} trong ${total}`,
      previousMatch: "Kết quả trước",
      nextMatch: "Kết quả tiếp theo",
      closeSearch: "Đóng tìm kiếm",
      loadOlder: "Tải tin nhắn cũ hơn",
      topicDriftTitle: "Cuộc trao đổi đang chuyển chủ đề",
      topicDriftDescription:
        "Từ “Bằng chứng khách hàng” sang “Chiến lược định giá”.",
      splitTopic: "Tạo cuộc trò chuyện mới",
      continueHere: "Tiếp tục tại đây",
      contextSources: "Kizuna đang sử dụng",
      draftSaved: "Bản nháp được lưu riêng cho cuộc trò chuyện này",
      categories: {
        general: "Trao đổi chung",
        material_analysis: "Phân tích tài liệu",
        decision_cycle: "Chu kỳ quyết định",
        readiness_review: "Review mức độ sẵn sàng",
        mentor_preparation: "Chuẩn bị phiên cố vấn",
        opportunity_review: "Đánh giá cơ hội",
      },
    },
    search: {
      title: "Tìm kiếm trong venture",
      description:
        "Tìm trong hội thoại, quyết định, bằng chứng, tài liệu và Venture Memory của venture hiện tại.",
      placeholder: "Tìm quyết định, bằng chứng hoặc tài liệu…",
      empty: "Không tìm thấy kết quả phù hợp",
      loading: "Đang tìm trong venture…",
      failed: "Tìm kiếm chưa hoàn tất. Truy vấn của bạn vẫn được giữ nguyên.",
      all: "Tất cả",
      contentType: "Loại nội dung",
      dateRange: "Thời gian",
      decisionCycle: "Chu kỳ quyết định",
      status: "Trạng thái",
      contributor: "Nguồn đóng góp",
      pinnedOnly: "Chỉ mục đã ghim",
      resultCount: (count) => `${count} kết quả`,
      types: {
        decision: "Quyết định",
        evidence: "Bằng chứng",
        conversation: "Hội thoại",
        document: "Tài liệu",
        mentor_session: "Phiên cố vấn",
        readiness: "Mức độ sẵn sàng",
        memory: "Bộ nhớ venture",
        opportunity: "Cơ hội",
        report: "Báo cáo",
      },
      groups: {
        decision: "Quyết định",
        evidence: "Bằng chứng",
        conversation: "Hội thoại",
        document: "Tài liệu",
        mentor_session: "Phiên cố vấn",
        readiness: "Mức độ sẵn sàng",
        memory: "Bộ nhớ venture",
        opportunity: "Cơ hội",
        report: "Báo cáo và tóm tắt",
      },
      dates: {
        all: "Mọi thời điểm",
        sevenDays: "7 ngày qua",
        thirtyDays: "30 ngày qua",
        older: "Cũ hơn 30 ngày",
      },
      contributors: {
        all: "Mọi nguồn",
        founder: "Founder",
        ai: "Kizuna AI",
        mentor: "Cố vấn",
        system: "Hệ thống",
      },
      cycles: {
        onboarding: "Onboarding Activation",
        pricing: "Thử nghiệm định giá",
      },
    },
    memory: {
      title: "Bộ nhớ venture",
      description:
        "Context có cấu trúc được xác nhận từ hội thoại, nguồn và quyết định.",
      verified: "Thông tin đã xác nhận",
      assumptions: "Giả định đang kiểm chứng",
      decisions: "Quyết định",
      evidence: "Bằng chứng",
      outcomes: "Kết quả",
      disputed: "Thông tin đang tranh luận",
      outdated: "Thông tin đã cũ",
      sources: (count) => `${count} nguồn`,
      updated: "Cập nhật",
      relatedCycle: "Chu kỳ liên quan",
      createdBy: "Nguồn tạo",
      confirm: "Xác nhận",
      dispute: "Tranh luận",
      markOutdated: "Đánh dấu đã cũ",
      viewHistory: "Xem lịch sử",
      freshnessWarning:
        "Thông tin có thể đã cũ và không nên dùng làm context chính.",
      updateValue: "Cập nhật số liệu",
      keepValue: "Giữ nguyên",
      noHistory: "Chưa có thay đổi trạng thái trước đó.",
      confirmUpdate: "Áp dụng thay đổi",
      cancelUpdate: "Hủy",
      versionConflict:
        "Bối cảnh đã thay đổi trong lúc bạn xác nhận. Chưa có cập nhật nào được áp dụng.",
      reloadContext: "Tải lại bối cảnh",
      compareChanges: "So sánh thay đổi",
      versionComparison: (expectedVersion, currentVersion) =>
        `Phiên bản bạn mở: ${expectedVersion} · Phiên bản hiện tại: ${currentVersion}`,
      creators: {
        founder: "Founder",
        ai: "Kizuna AI",
        mentor: "Cố vấn",
        system: "Hệ thống",
      },
      statuses: {
        verified: "Đã xác minh",
        inferred: "AI suy luận",
        assumed: "Giả định",
        disputed: "Đang tranh luận",
        missing: "Còn thiếu",
        outdated: "Đã cũ",
        superseded: "Đã được thay thế",
      },
    },
    conflict: {
      title: "Tôi phát hiện context đang mâu thuẫn",
      description:
        "Chọn cách diễn giải canonical mà không xóa lịch sử nguồn cũ.",
      setCurrent: "Đặt làm hiện tại",
      futureDirection: "Giữ làm hướng tương lai",
      parallelHypotheses: "Giữ như giả thuyết song song",
      resolved: "Mâu thuẫn đã được giải quyết",
      current: "Hiện tại",
      older: "Nguồn cũ hơn",
      outdated: "Đã cũ",
    },
    summary: {
      title: "Tóm tắt phiên làm việc",
      description:
        "Chỉnh sửa checkpoint trước khi xác nhận hoặc cập nhật Venture Memory.",
      confirm: "Xác nhận tóm tắt",
      updateMemory: "Cập nhật Venture Memory",
      skip: "Bỏ qua",
      draft: "Bản nháp",
      confirmed: "Founder đã xác nhận",
      memoryUpdated: "Đã cập nhật bộ nhớ",
      editItem: "Chỉnh sửa mục",
      saved: "Thay đổi đã được giữ trong bản nháp",
    },
    timeline: {
      title: "Dòng thời gian quyết định",
      description:
        "Chỉ hiển thị thay đổi có ý nghĩa đối với venture.",
      compare: "So sánh trước và sau",
      openCycle: "Mở chu kỳ liên quan",
      openEvidence: "Mở bằng chứng",
      readinessHistory: "Lịch sử mức độ sẵn sàng",
      previousScore: "Điểm trước",
      nextScore: "Điểm mới",
      evidenceAdded: "Bằng chứng được thêm",
      evidenceRemoved: "Bằng chứng bị loại",
      rubric: "Phiên bản tiêu chí",
      rubricWarning:
        "Hai mức điểm dùng phiên bản tiêu chí khác nhau nên không thể so sánh trực tiếp.",
      changeLabel: (delta) =>
        `Thay đổi ${delta >= 0 ? "tăng" : "giảm"} ${Math.abs(delta)} điểm`,
    },
    documents: {
      title: "Phiên bản tài liệu",
      description:
        "Theo dõi nguồn canonical và các phụ thuộc có cấu trúc.",
      canonical: "Canonical",
      current: "Hiện tại",
      superseded: "Đã được thay thế",
      archived: "Đã lưu trữ",
      compare: "So sánh phiên bản",
      markCanonical: "Đặt làm canonical",
      archive: "Lưu trữ",
      delete: "Xóa",
      deleteTitle: "Tài liệu đang được dùng làm nguồn",
      deleteDescription:
        "Xóa tài liệu sẽ giữ lịch sử nhưng đánh dấu các bản ghi phụ thuộc là mất nguồn.",
      deleteAndMarkMissing: "Xóa và đánh dấu mất nguồn",
      chooseReplacement: "Đặt tài liệu khác làm nguồn",
      dependencyMemory: (count) => `${count} thông tin venture`,
      dependencyReadiness: (count) => `${count} chiều readiness`,
      dependencyCycles: (count) =>
        `${count} chu kỳ quyết định đang hoạt động`,
    },
    saved: {
      title: "Đã ghim",
      description:
        "Mỗi mục ghim tham chiếu tới nguồn gốc thay vì nhân bản dữ liệu.",
      openOriginal: "Mở bản gốc",
      empty: "Chưa có mục nào được ghim",
    },
    surfaces: {
      pulse: "Venture Pulse",
      memory: "Bộ nhớ",
      summary: "Tóm tắt",
      timeline: "Dòng thời gian",
      documents: "Tài liệu",
      pinned: "Đã ghim",
    },
  },
};
